In [ ]:
# flask 웹서버 기능 5000번 포트로 서비스


In [2]:
import matplotlib # 시각화 패키지
import numpy as np # 별칭, class로 구성
print(np.__version__) # 상위 오브젝트가 가진 속성
def pprint(arr): # nparray : numpy의 기본 데이터 배열
    print("type:{}".format(type(arr)))
    print("shape:{}, dimension:{}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data:\n", arr)
    # 숫자의 디폴트는 int32
arr = [1.0,2.0,3.0] # 리스트
a = np.array([1,2,3]) # ndarray 생성함수 (매개변수 : 리스트)
pprint(a)

1.16.5
type:<class 'numpy.ndarray'>
shape:(3,), dimension:1, dtype:int32
Array's Data:
 [1 2 3]


In [4]:
# np : 인스턴스상태, array 함수 호출, 매개변수로 리스트를 받아서 ndarray 생성
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(id(a)) # 주소값 확인
print(a.size) # 데이터 개수
print(a.astype(np.float32)) # 데이터타입 변경 (numpy 행중심, 동질적이므로 한번에 바꿀 수 있음)
print(a.dtype.itemsize*a.size) # float32의 사이즈 * 데이터 개수 = 전체 메모리 사이즈 (바이트)
# iterator (python : for in range => list 생성)
a = np.arange(1000) # arange => ndarray 생성 
a

2153976190896
10
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
40


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [6]:
# nparray 초기화 함수들
print(np.zeros((3,4))) # 0으로 채워짐
print(np.ones((2,3,4), dtype=np.int16)) # 1로 채움, 3 차원 (면, 행, 열)
print(np.full((2,2),7)) # 2행 2열을 7로 채워라
print(np.eye(4)) # 대각행렬 (identity), 행렬연산에서 항등원
print(np.empty((4,2))) # 쓰레기값 (기존 메모리에 있는 값 @_@)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 5.53353523e-321]
 [1.24611470e-306 8.90060779e-307]]


In [7]:
a = np.arange(0, 100, 10) # ndarray
indices = [1,5,-1] # list
print(indices)
b = a[indices] # 리스트를 첨자로 사용
print(a)
print(b)

[1, 5, -1]
[ 0 10 20 30 40 50 60 70 80 90]
[10 50 90]


In [13]:
a = np.arange(11,36) # 1차원
a.shape = (5,5) # 정상 모양을 갖춘 개수
print(a)
print(type(a))
print(a.dtype)
print(a.size)
print(a.shape) # 차수 (5,5)
print(a.ndim) # 2차원
print(a.nbytes) # 25개 데이터, 각 4바이트
print(a.strides) # 다음 열 / 행의 데이터는 몇 바이트를 건너뛰어야하는기

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
<class 'numpy.ndarray'>
int32
25
(5, 5)
2
100
(20, 4)


In [16]:
arr = np.arange(10)
print(type(arr))
print(arr)
print(arr[5])
print(arr[5:8]) # 마지막 불포함
arr[5:8] = 12 # 데이터 업데이트
print(arr[1:6])
print(arr)

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 1  2  3  4 12]
[ 0  1  2  3  4 12 12 12  8  9]


In [19]:
# numpy 첨자 생략 불가 [,4] 이런거 안됨
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[0]) # 행우선 : 행
print(arr2d[0][2])
print(arr2d[0,2])
print(arr2d[:2]) # 0,1행
print(arr2d[:2, 1:])
print(arr2d[1,:2]) 
print(arr2d[2,:1])
arr2d[:2,:1]=0
arr2d[2,2]=0
print(arr2d)

[1 2 3]
3
3
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[4 5]
[7]
[[0 2 3]
 [0 5 6]
 [7 8 0]]


In [21]:
# 실제 저장은 일렬로, 사람이 데이터를 다루는 것은 입체로 (480바이트)
# 행렬연산에서 앞의 행렬열수와 뒤의 행렬의 행수를 일치 시켜야 행렬곱이 가능
# 행렬 곱에서 앞뒤를 바꾸면 안됨
print("스트라이드의 값", np.ones((3,4,5), dtype=np.float64).strides)
# 단일데이터라 float64라서 8바이트 / 한 행을 지나가려면 8 * 5개 / 한 열을 지나가려면 40 * 4

스트라이드의 값 (160, 40, 8)


In [28]:
# 문제
arr3d = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[10,11,12]]]) # 2면 2행 3열
print('첫면은', arr3d[0])
print('첫차원 첫행은', arr3d[0][0])
print('첫차원 첫행은', arr3d[0,0])
print('첫요소는', arr3d[0,0,0])

첫면은 [[1 2 3]
 [4 5 6]]
첫차원 첫행은 [1 2 3]
첫차원 첫행은 [1 2 3]
첫요소는 1


In [26]:
# 8 을 출력해보세용
arr3d[1][0][1]
arr3d[1,0,1]
# 12를 출력해보세용
arr3d[1,1,2] # 1을 빼줘야 올바른 인덱스~

12

In [27]:
# 백업이 안됨 (대입하면 같은 주소를 가리키지 때문에)
old_values = arr3d # 대입 : 주소를 복사
arr3d[0] = 43
print("값의 변경후")
print(arr3d)
print("이전 값으로 복구")
arr3d = old_values # 복구가 안도ㅑ아
print(arr3d)

값의 변경후
[[[43 43 43]
  [43 43 43]]

 [[ 7  8  9]
  [10 11 12]]]
이전 값으로 복구
[[[43 43 43]
  [43 43 43]]

 [[ 7  8  9]
  [10 11 12]]]


In [30]:
# 그래서 copy가 있쥐!
old_values = arr3d.copy()
arr3d[0] = 43
print("값의 변경후")
print(arr3d)
print("이전 값으로 복구")
arr3d = old_values
print(arr3d)

값의 변경후
[[[43 43 43]
  [43 43 43]]

 [[ 7  8  9]
  [10 11 12]]]
이전 값으로 복구
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [32]:
Z = np.arange(36)
print(Z)
Z = Z.reshape((6,6))
print(Z)
reshape2 = Z.reshape((2,3,6))
print(reshape2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [35]:
arr = np.arange(32).reshape((8,4))
print(arr)
print(arr[[1,5,7,2]]) # 행중심
print(arr[[-1,-5,-7,-2]]) # 거꾸로 인덱싱
print(arr[[1,5,7,2],[0,3,1,2]])
# fancy 인덱싱
print(arr[[1,2,5,7]][:,[0,1,2,3]])
print(arr[[1,5,7,2]][:,[0,3,1,2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]
[[28 29 30 31]
 [12 13 14 15]
 [ 4  5  6  7]
 [24 25 26 27]]
[ 4 23 29 10]
[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]
 [28 29 30 31]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [39]:
print(arr[[1,5,7,2]][[0,3,1,2]])
print(arr[[1,5,7,2]][:,[0,3,1,2]])

[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]
 [28 29 30 31]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [50]:
# 문제
arr = []
for i in range(6):
    ad = []
    for j in range(6):
        ad.append(i*10 + j) # 인덱싱 식 (위치를 찾아낼 때 쓰는 식)
    arr.append(ad)
print(arr)
arr = np.array(arr)

[[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15], [20, 21, 22, 23, 24, 25], [30, 31, 32, 33, 34, 35], [40, 41, 42, 43, 44, 45], [50, 51, 52, 53, 54, 55]]


In [79]:
print("주황색", arr[[0,1,2,3,4],[1,2,3,4,5]])
print("빨강색", arr[[0,2,5],2])
print("하늘색", arr[3:6][:,[0,2,5]])

주황색 [ 1 12 23 34 45]
빨강색 [ 2 22 52]
하늘색 [[30 32 35]
 [40 42 45]
 [50 52 55]]


In [102]:
print("빨강색", arr[:,2])
print("주황색", arr[0,3:5])
print("연두색", arr[[2,4]][:,[0,2,4]])
print("하늘색", arr[4:,4:])
print("하늘색", arr[[4:]][:,[4,5]])

빨강색 [ 2 12 22 32 42 52]
주황색 [3 4]
연두색 [[20 22 24]
 [40 42 44]]
하늘색 [[44 45]
 [54 55]]
하늘색 [[44 45]
 [54 55]]


In [107]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) # 4 X 3
v = np.array([1,0,1])
print("타일출력")
vv = np.tile(v, (4,1))
print(vv)
y = x + vv # 배열연산 (요소별, +/-/*/%)
print(y)
# 배열연산 : 양쪽 차원이 일치해야 함
print(x + v) # 4X3 과 1X3 연산 가능 : 브로드캐스팅
print(x + 3) # 상수는 브로드캐스팅되어서 각 요소와 연산

타일출력
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [113]:
x = np.arange(6).reshape((3,2))
print(x)
# 거듭제곱 (행렬 곱)
# x@x 오류남 (앞의 행렬 열수와 뒤의 행렬 행수가 일치해야 함) 
# 전치행렬
x@x.T
print(np.transpose(x))

[[0 1]
 [2 3]
 [4 5]]
[[0 2 4]
 [1 3 5]]


In [118]:
arr = np.arange(24).reshape((2,3,4))
print(arr)
print(arr.transpose((1,0,2))) # 보는 방향을 바꾼다고 생각~_~
print(arr.transpose((0,2,1)))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]


In [137]:
# Boolean indexing (True / False)
names = np.array(['Seoul', 'Daejun', 'chungju', 'seoul', 'chungju', 'Daejun', 'Daejun'])
data = np.random.randn(7,4)
print(names=='Seoul')
print(data[names=='Seoul']) # 1,0,0,0,0,0,0
print(data[names=='Seoul',2:]) # 0번행만 출력해랏
print(data[names=='Seoul',3])
print(names !='Seoul') # 아래와 같은 의미
print(~(names=='Seoul'))
mask = (names =='Seoul')|(names=='chungju')
print(mask)
print(data[mask])

[ True False False False False False False]
[[ 0.53372521 -0.77441967 -0.17113258  0.00574966]]
[[-0.17113258  0.00574966]]
[0.00574966]
[False  True  True  True  True  True  True]
[False  True  True  True  True  True  True]
[ True False  True False  True False False]
[[ 0.53372521 -0.77441967 -0.17113258  0.00574966]
 [ 0.09599037 -1.77422459  0.9226051  -0.10135873]
 [ 1.14244534 -0.68615324 -0.76819833  1.51647544]]


In [138]:
print(data)

[[ 0.53372521 -0.77441967 -0.17113258  0.00574966]
 [ 0.62628893 -0.4762041  -0.19925411 -0.03808365]
 [ 0.09599037 -1.77422459  0.9226051  -0.10135873]
 [-1.45203142  0.9991751  -0.91987604  0.74669334]
 [ 1.14244534 -0.68615324 -0.76819833  1.51647544]
 [-1.16841993  0.9030081   0.78851803  0.50034824]
 [ 0.91769056 -0.81904441  0.82881306 -0.72064028]]


In [139]:
print(data[names=='Seoul'])

[[ 0.53372521 -0.77441967 -0.17113258  0.00574966]]


In [136]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
print(zip(xarr, yarr, cond)) # zip 요소별로 데이터를 묶음
print(list(zip(xarr, yarr, cond)))
result = [(x if c else y) for x,y,c in zip(xarr, yarr, cond)]
print("result = ", result)

result = np.where(cond, xarr, yarr)
print(result)

arr = np.random.randn(4,4)
print(arr)
print(np.where(arr>0, 2, -2))

[(1.1, 2.1, True), (1.2, 2.2, False), (1.3, 2.3, True), (1.4, 2.4, True), (1.5, 2.5, False)]
result =  [1.1, 2.2, 1.3, 1.4, 2.5]
[1.1 2.2 1.3 1.4 2.5]
[[ 1.03344505 -0.34749709  0.8905179   1.02384287]
 [-0.19613577 -0.75932237  1.0574087  -0.62807598]
 [ 0.66995886 -0.1288029   0.08093912  0.3218589 ]
 [ 0.17098987 -1.33234803  0.14406451 -0.77012786]]
[[ 2 -2  2  2]
 [-2 -2  2 -2]
 [ 2 -2  2  2]
 [ 2 -2  2 -2]]


In [ ]:
# 문제 ) 다음 데이터를 이용하여 두개 다 참일 때는 0, cond1이 참일 때는 1, cond2가 참일때는 2,
# 그 외일 때는 3으로 처리하여 출력하도록 하시오

In [163]:
result = []
cond1 = np.array([1,0,1,1,0,0,1], dtype=bool)
cond2 = np.array([0,1,1,1,0,1,1], dtype=bool)

# 나의 풀이
result = np.where(cond1>0, (np.where(cond2>0, 0, 1)), (np.where(cond2>0, 2, 3)))
print(result)

[1 2 0 0 3 2 0]


In [168]:
# 쌤의 풀이 1
result = []
for i in range(len(cond1)):
    if(cond1[i] and cond2[i]):
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)
print("조건문", result)
# 쌤의 풀이 2
result = np.where(cond1&cond2, 0, np.where(cond1, 1, np.where(cond2, 2, 3)))
print("3항 연산자", result)
# 쌤의 풀이 3
result = 1*(cond1&~cond2) + 2*(cond2&~cond1) + 3*~(cond1|cond2)
print("수식을 이용한", result)

조건문 [1, 2, 0, 0, 3, 2, 0]
3항 연산자 [1 2 0 0 3 2 0]
수식을 이용한 [1 2 0 0 3 2 0]


In [170]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

z = np.zeros_like(x) # x와 형태가 같은 공간을 확보해줌 (다른 행렬과 같은 사이즈로 초기화)
for i in range(10000):
    z[i] = x[i] + y[i]

In [174]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
print(np.all(a==b)) # 전체가 참일 때 참
print(np.any(a==b)) # 하나라도 참이면 참
print(np.exp(a)) # 지수함수 (자연대수 : 2.718)

False
True
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
# 선형대수 : 선형으로 해결하자 => 비선형도 잘게 나누어보면 선형이다
# (참고) 외적 - 두 개의 벡터가 만드는 면에 수직인 벡터
# 내적은 스칼라값(의미 = 두 벡터의 사이각), 외적은 벡터!

In [ ]:
# 행렬 (연립방정식의 해 구하기 위해서는 역행렬이 필요)
# (분해를 해놓으면 역행렬을 더 빠르게 구할 수 있더라) => 고유값분해, 특이행렬분해
# 고유값분해(정방행렬 = 행과 열수가 같은 행렬 ex. 공분산행렬, 상관계수행렬 _공분산을 표준화시킨 것, -1~1사이) : 고유치+고유벡터
# ㄴ PCA (pricinal Conponent Analysis) *현장에서 사운드를 통해 불량확인할 때 잡음 제거는 필수. 그 때 필요한 게 PCA
# 특이행렬분해
# ㄴ SVD (Singular Value Decomposition) *희소행렬에서 특징 추출할 때 사용
# 행렬 연산의 목적 : 특징 추출

In [ ]:
# 행열의 종류
- 정방행열 :정사각형 (행과 열수가 같은 행렬)
- 대칭행열 : 우상단과 좌하단 같은 것
- 대각행열 : scale 을 변화시키는 요소
- 단위행열 (identity) : 행렬곱의 항등원 (행렬 곱하기 역행열 = 단위행열)
- 역행열 : 행열의 나눗셈을 위해 구해서 곱해지는 행열 (정방행열만 가능)
- 특이행열 : 역행열이 없는 행렬
- 직교행열 : 축의 정직교, 각 축간의 내적이 0인 행열
    
정방행열이면서 대칭행열 - 공분산행열, 상관계수행열, 거리행열
공분산 : 두 수간의 관계 (x -xm)(y - ym) / (n-1) *n-1 자유도
상관계수 : 표준화된 값, -1~1 사이의 값, 공분산을 두 수의 표준편차의 곱으로 나눠준 값

In [176]:
import numpy as np
F1 = np.array([[1,2],[3,4]])
F2 = np.array([[2,2],[2,2]])
print(F1)
print(F2)
print(F1+F2)
print(F1*F2)
print(F1@F2)

[[1 2]
 [3 4]]
[[2 2]
 [2 2]]
[[3 4]
 [5 6]]
[[2 4]
 [6 8]]
[[ 6  6]
 [14 14]]


In [186]:
# 방정식의 해
A = np.array([[2,1,-2],[3,0,1],[1,1,-1]])
b = np.transpose(np.array([[-3,5,-2]])) # 열로 전치
print(b)
x = np.linalg.solve(A,b) # A의 역행렬을 구해서 b와 곱해줌
print(x)

[[-3]
 [ 5]
 [-2]]
[[ 1.]
 [-1.]
 [ 2.]]


In [187]:
np.dot(np.linalg.inv(A),b)

array([[ 1.],
       [-1.],
       [ 2.]])

In [188]:
np.linalg.inv(A)@b

array([[ 1.],
       [-1.],
       [ 2.]])

In [189]:
a = np.array([0,1,0])
b = np.array([1,0,0])
res = np.dot(a,b)
print(res) # 내적이 0이면 직각

0


In [194]:
print(np.linalg.norm(a)) # 벡터의 크기
print(np.linalg.norm(b))
print(np.linalg.norm(a)*np.linalg.norm(b))
rad = res / (np.linalg.norm(a)*np.linalg.norm(b)) #cos theta값
print("cos theta", rad)
print(np.arccos(rad)) # theta 값을 구함
print(np.degrees(np.arccos(rad)))

1.0
1.0
1.0
cos theta 0.0
1.5707963267948966
90.0


In [195]:
x = np.array([[1,2],[3,4]])
y = np.linalg.inv(x)
print(x)
print(y)
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [199]:
# 다음 방정식의 해를 구하고 검산하시오

- x + y + z = 6
- 2y + 5z = -4
- 2x + 5y - z = 27

SyntaxError: invalid syntax (<ipython-input-199-e9e2a1dd5931>, line 4)

In [216]:
A = np.array([[1,1,1],[0,2,5],[2,5,-1]])
b = np.transpose(np.array([[6, -4, 27]]))
print(b)
result = np.linalg.inv(A)@b

[[ 6]
 [-4]
 [27]]


In [215]:
result2 = np.linalg.solve(A,b)
print(result2)

[[ 5.]
 [ 3.]
 [-2.]]


In [219]:
result3 = np.dot(np.linalg.inv(A), b)
print(result3)

[[ 5.]
 [ 3.]
 [-2.]]


In [207]:
print(result)

[[ 5.]
 [ 3.]
 [-2.]]


In [208]:
5 + 3 - 2

6

In [210]:
2*3 + 5 * (-2)

-4

In [211]:
2*5 + 5*3 + (-1)*(-2)

27